declare const VERSION = "Celestra v7.2.0";
type ObjectLike = Record<PropertyKey, any>;
type Numeric = number | bigint;
type IterableLike = Iterable<any> | Iterator<any> | IterableIterator<any>;
type Nullish = undefined | null;
type NonNullablePrimitive = boolean | number | bigint | string | symbol;
type Primitive = Nullish | NonNullablePrimitive;
type Comparable = number | bigint | string | boolean | Date;
type AsyncFunction<T> = (...args: ReadonlyArray<any>) => Promise<T>;
type ArrowFunction<Args extends any[] = [], R = any> = (this: void, ...args: Args) => R;
type TypedArray = Exclude<ArrayBufferView, DataView>;
type ClearCookiesOptions = {
    path?: string;
    domain?: string;
    secure?: boolean;
    SameSite?: string;
    HttpOnly?: boolean;
};
declare const BASE16 = "0123456789ABCDEF";
declare const BASE32 = "234567ABCDEFGHIJKLMNOPQRSTUVWXYZ";
declare const BASE36 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
declare const BASE58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
declare const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
declare const WORDSAFEALPHABET = "23456789CFGHJMPQRVWXcfghjmpqvwx";
declare function assert(condition: unknown, message?: unknown): asserts condition;
declare const eq: (value1: unknown, value2: unknown) => boolean;
declare const gt: (value1: Comparable, value2: Comparable) => boolean;
declare const gte: (value1: Comparable, value2: Comparable) => boolean;
declare const lt: (value1: Comparable, value2: Comparable) => boolean;
declare const lte: (value1: Comparable, value2: Comparable) => boolean;
declare const tap: (callback: Function) => Function;
declare function once(callback: Function): Function;
declare function curry(callback: Function): Function;
declare const pipe: (...functions: Function[]) => Function;
declare const compose: (...functions: Function[]) => Function;
declare const pick: (obj: ObjectLike, keys: string[]) => ObjectLike;
declare const omit: (obj: ObjectLike, keys: string[]) => ObjectLike;
declare const assoc: (obj: ObjectLike, key: string, value: unknown) => ObjectLike;
declare function asyncNoop(): Promise<void>;
declare function asyncT(): Promise<boolean>;
declare function asyncF(): Promise<boolean>;
declare function asyncConstant<T>(value: T): AsyncFunction<T>;
declare function asyncIdentity(value: unknown): Promise<unknown>;
declare function randomUUIDv7(v4?: boolean): string;
declare const delay: (milisec: number) => Promise<void>;
declare const randomBoolean: () => boolean;
declare function deepAssign(target: unknown, ...sources: unknown[]): unknown;
declare const sizeIn: (object: object) => number;
declare const unBind: (callback: Function) => Function;
declare const bind: (thisArg: any, ...argArray: any[]) => any;
declare const constant: <T>(value: T) => (() => T);
declare const identity: <T>(value: T) => T;
declare function noop(): void;
declare const T: () => true;
declare const F: () => false;
declare function timestampID(size?: number, alphabet?: string): string;
declare const b64Encode: (str: unknown) => string;
declare const b64Decode: (str: unknown) => string;
declare function strCount(str: unknown, substr: unknown): number;
declare function strTruncate(str: string, newLength: number, omission?: string): string;
declare const strPropercase: (str: unknown) => string;
declare const strTitlecase: typeof strPropercase;
declare function strCapitalize(str: unknown): string;
declare function strUpFirst(str: unknown): string;
declare function strDownFirst(str: unknown): string;
declare const strReverse: (str: unknown) => string;
declare const strCodePoints: (str: unknown) => Array<number | undefined>;
declare const strFromCodePoints: ([...array]: Iterable<number>) => string;
declare function strAt(str: string, index: number, newChar?: string): string;
declare const strSplice: (str: string, index: number, count: number, ...add: string[]) => string;
declare const strHTMLRemoveTags: (str: unknown) => string;
declare const strHTMLEscape: (str: unknown) => string;
declare const strHTMLUnEscape: (str: unknown) => string;
declare const qsa: (str: string, context?: Document | HTMLElement) => HTMLElement[];
declare const qs: (str: string, context?: Document | HTMLElement) => HTMLElement | null;
declare function domReady(callback: Function): void;
declare function domCreate(elementType: string | ObjectLike, properties: object, innerHTML: string): HTMLElement;
declare function domToElement(str: string): Element | null;
declare const domGetCSS: (element: HTMLElement, property: string | number) => string | CSSStyleDeclaration;
declare function domSetCSS(element: HTMLElement, property: string | object, value: string): void;
declare function domFadeIn(element: HTMLElement, duration: number, display: string): void;
declare function domFadeOut(element: HTMLElement, duration: number): void;
declare function domFadeToggle(element: HTMLElement, duration: number, display?: string): void;
declare const domHide: (element: HTMLElement) => void;
declare const domShow: (element: HTMLElement, display?: string) => void;
declare function domToggle(element: HTMLElement, display?: string): void;
declare const domIsHidden: (element: HTMLElement) => boolean;
declare function domSiblings(element: Element): Element[];
declare function domSiblingsPrev(element: Element): Element[];
declare const domSiblingsLeft: typeof domSiblingsPrev;
declare function domSiblingsNext(element: Element): Element[];
declare const domSiblingsRight: typeof domSiblingsNext;
declare function importScript(...scripts: string[]): void;
declare function importStyle(...styles: string[]): void;
declare function form2array(form: HTMLFormElement): object[];
declare function form2string(form: HTMLFormElement): string;
declare const getDoNotTrack: () => boolean;
declare function getLocation(successCallback: PositionCallback, errorCallback?: PositionErrorCallback): void;
declare function createFile(filename: string, content: string, dataType?: string): void;
declare const getFullscreen: () => Document | Element | undefined;
declare function setFullscreenOn(element: HTMLElement | string): void;
declare function setFullscreenOff(): void;
declare const domGetCSSVar: (name: string) => string;
declare const domSetCSSVar: (name: string, value: string | null) => void;
declare const domScrollToTop: () => void;
declare const domScrollToBottom: () => void;
declare const domScrollToElement: (element: HTMLElement, top?: boolean) => void;
declare const domClear: (element: Element) => void;
declare const constructorOf: (value: unknown) => Function | undefined;
declare const isNonNullable: (value: unknown) => value is NonNullable<unknown>;
declare const isNonNullablePrimitive: (value: unknown) => value is NonNullablePrimitive;
declare function isArrowFunction(value: unknown): value is ArrowFunction;
declare const isAsyncIterator: (value: unknown) => value is AsyncIterator<unknown>;
declare function isTypedCollection(iter: IterableLike, expectedType: string | Function | Array<string | Function>, Throw?: boolean): boolean;
declare function is(value: unknown, expectedType: string | Function | (string | Function)[]): boolean;
declare function toSafeString(value: unknown): string;
declare const isPropertyKey: (value: unknown) => value is PropertyKey;
declare const toPropertyKey: (value: unknown) => PropertyKey;
declare const isIndex: (value: unknown) => value is number;
declare function toIndex(value: number): number;
declare const typeOf: (value: unknown) => string;
declare const isSameType: (value1: unknown, value2: unknown, type?: string) => boolean;
declare const isSameInstance: (value1: unknown, value2: unknown, Contructor: Function) => boolean;
declare function isCoercedObject(value: unknown): Function | boolean;
declare function isDeepStrictEqual(value1: unknown, value2: unknown): boolean;
declare function isEmpty(value: unknown): boolean;
declare const isProxy: (value: unknown) => boolean;
declare const isAsyncGeneratorFunction: (value: unknown) => value is AsyncGeneratorFunction;
declare function isPlainObject(value: unknown): boolean;
declare const isObject: (value: unknown) => value is object;
declare const isFunction: (value: unknown) => value is Function;
declare function isArraylike<T>(value: unknown): value is ArrayLike<T>;
declare const isNull: (value: unknown) => value is null;
declare const isUndefined: (value: unknown) => value is undefined;
declare const isNullish: (value: unknown) => value is Nullish;
declare const isPrimitive: (value: unknown) => value is Primitive;
declare const isIterator: <T>(value: unknown) => value is Iterator<T>;
declare const isRegexp: (value: unknown) => value is RegExp;
declare const isElement: (value: unknown) => boolean;
declare const isIterable: (value: unknown) => value is Iterable<unknown>;
declare const isAsyncIterable: <T>(value: unknown) => value is AsyncIterable<T>;
declare const isTypedArray: (value: unknown) => value is TypedArray;
declare const isGeneratorFunction: (value: unknown) => value is GeneratorFunction;
declare const isAsyncFunction: <T>(value: unknown) => value is AsyncFunction<T>;
declare function setCookie(name: string | ObjectLike, value: string, hours: number | undefined, path: string | undefined, domain: string, secure: boolean, SameSite: string | undefined, HttpOnly: boolean): void;
declare function getCookie(name: string): string | null | ObjectLike;
declare function hasCookie(name: string): boolean;
declare function removeCookie(name: string | ObjectLike, path: string | undefined, domain: string, secure: boolean, SameSite: string | undefined, HttpOnly: boolean): boolean;
declare function clearCookies(path?: string | ClearCookiesOptions, domain?: string, secure?: boolean, SameSite?: string | undefined, HttpOnly?: boolean): void;
declare const castArray: (value: unknown) => unknown[];
declare const compact: (iter: IterableLike) => Iterator<unknown>;
declare function unique(iter: IterableLike, resolver?: string | Function | null | undefined): unknown[] | void;
declare const count: (iter: IterableLike, callback: Function) => number;
declare function arrayDeepClone([...array]: unknown[]): unknown[];
declare function initial(iter: IterableLike): Iterable<unknown>;
declare function shuffle([...array]: unknown[]): unknown[];
declare const min: (...args: unknown[]) => unknown;
declare const max: (...args: unknown[]) => unknown;
declare const arrayRepeat: (value: unknown, num?: number) => unknown[];
declare const arrayCycle: ([...array]: unknown[], num?: number) => unknown[];
declare const arrayRange: (start?: number, end?: number, step?: number) => unknown[];
declare function zip(...args: unknown[]): unknown[];
declare const unzip: ([...array]: unknown[]) => unknown[];
declare function zipObj([...array1]: unknown[], [...array2]: unknown[]): ObjectLike;
declare const arrayAdd: (array: unknown[], value: unknown) => boolean;
declare function arrayClear(array: unknown[]): unknown[];
declare function arrayRemove(array: unknown[], value: unknown, all?: boolean): boolean;
declare function arrayRemoveBy(array: unknown[], callback: (value: unknown, index: number, obj: unknown[]) => unknown, all?: boolean): boolean;
declare function arrayMerge(target: unknown[], ...sources: unknown[]): unknown[];
declare function iterRange(start?: number, step?: number, end?: number): Generator<number, void, unknown>;
declare function iterCycle([...array]: unknown[], num?: number): Iterator<unknown>;
declare function iterRepeat(value: unknown, num?: number): Iterator<unknown>;
declare function slice(iter: IterableLike, begin?: number, end?: number): Iterator<unknown>;
declare function tail(iter: IterableLike): Iterator<unknown>;
declare function item<T>(iter: IterableLike, pos: number): T | undefined;
declare const nth: typeof item;
declare function size(value: unknown): number;
declare function first<T>(iter: IterableLike): T | undefined;
declare const head: typeof first;
declare const last: (iter: IterableLike) => unknown;
declare function reverse([...array]: unknown[]): Iterator<unknown>;
declare const sort: ([...array]: unknown[], numbers?: boolean) => unknown[];
declare function includes(collection: unknown, value: unknown, comparator?: Function): boolean;
declare const findLast: (iter: IterableLike, callback: Function) => unknown;
declare function concat(...iterables: unknown[]): Iterator<unknown>;
declare function join(iter: IterableLike, separator?: string): string;
declare function add(value1: number, value2: number): number;
declare function add(value1: bigint, value2: bigint): bigint;
declare function sub(value1: number, value2: number): number;
declare function sub(value1: bigint, value2: bigint): bigint;
declare function mul(value1: number, value2: number): number;
declare function mul(value1: bigint, value2: bigint): bigint;
declare function div(value1: number, value2: number): number;
declare function div(value1: bigint, value2: bigint): bigint;
declare function divMod(value1: number, value2: number): number;
declare function divMod(value1: bigint, value2: bigint): bigint;
declare function mod(value1: number, value2: number): number;
declare function mod(value1: bigint, value2: bigint): bigint;
declare const isFloat: (value: unknown) => boolean;
declare function toInteger(value: unknown): number;
declare const toIntegerOrInfinity: (value: unknown) => number;
declare function sum(...args: Numeric[]): Numeric;
declare const avg: (...args: number[]) => number;
declare function product(first: number, ...args: number[]): number;
declare function product(first: bigint, ...args: bigint[]): bigint;
declare function pow(base: number, power: number): number;
declare function pow(base: bigint, power: bigint): bigint;
declare function clamp(value: number, min: number, max: number): number;
declare function clamp(value: bigint, min: bigint, max: bigint): bigint;
declare const minmax: typeof clamp;
declare const isEven: (value: unknown) => boolean;
declare const isOdd: (value: unknown) => boolean;
declare const signbit: (value: unknown | Numeric) => boolean;
declare function randomInt(min?: number | undefined, max?: number | null | undefined): number;
declare function randomFloat(min?: number | undefined, max?: number | null | undefined): number;
declare function inRange(value: number, min: number, max: number): boolean;
declare function inRange(value: bigint, min: bigint, max: number): boolean;
declare const _default: {
    VERSION: string;
    BASE16: string;
    BASE32: string;
    BASE36: string;
    BASE58: string;
    BASE62: string;
    WORDSAFEALPHABET: string;
    assert: typeof assert;
    eq: typeof eq;
    gt: typeof gt;
    gte: typeof gte;
    lt: typeof lt;
    lte: typeof lte;
    tap: typeof tap;
    once: typeof once;
    curry: typeof curry;
    pipe: typeof pipe;
    compose: typeof compose;
    pick: typeof pick;
    omit: typeof omit;
    assoc: typeof assoc;
    asyncNoop: typeof asyncNoop;
    asyncT: typeof asyncT;
    asyncF: typeof asyncF;
    asyncConstant: typeof asyncConstant;
    asyncIdentity: typeof asyncIdentity;
    randomUUIDv7: typeof randomUUIDv7;
    delay: typeof delay;
    randomBoolean: typeof randomBoolean;
    deepAssign: typeof deepAssign;
    sizeIn: typeof sizeIn;
    unBind: typeof unBind;
    bind: (thisArg: any, ...argArray: any[]) => any;
    constant: typeof constant;
    identity: typeof identity;
    noop: typeof noop;
    T: typeof T;
    F: typeof F;
    timestampID: typeof timestampID;
    b64Encode: typeof b64Encode;
    b64Decode: typeof b64Decode;
    strCount: typeof strCount;
    strTruncate: typeof strTruncate;
    strPropercase: typeof strPropercase;
    strTitlecase: typeof strPropercase;
    strCapitalize: typeof strCapitalize;
    strUpFirst: typeof strUpFirst;
    strDownFirst: typeof strDownFirst;
    strReverse: typeof strReverse;
    strCodePoints: typeof strCodePoints;
    strFromCodePoints: typeof strFromCodePoints;
    strAt: typeof strAt;
    strSplice: typeof strSplice;
    strHTMLRemoveTags: typeof strHTMLRemoveTags;
    strHTMLEscape: typeof strHTMLEscape;
    strHTMLUnEscape: typeof strHTMLUnEscape;
    constructorOf: typeof constructorOf;
    isNonNullable: typeof isNonNullable;
    isNonNullablePrimitive: typeof isNonNullablePrimitive;
    isArrowFunction: typeof isArrowFunction;
    isAsyncIterator: typeof isAsyncIterator;
    isTypedCollection: typeof isTypedCollection;
    is: typeof is;
    toSafeString: typeof toSafeString;
    isPropertyKey: typeof isPropertyKey;
    toPropertyKey: typeof toPropertyKey;
    isIndex: typeof isIndex;
    toIndex: typeof toIndex;
    typeOf: typeof typeOf;
    isSameType: typeof isSameType;
    isSameInstance: typeof isSameInstance;
    isCoercedObject: typeof isCoercedObject;
    isDeepStrictEqual: typeof isDeepStrictEqual;
    isEmpty: typeof isEmpty;
    isProxy: typeof isProxy;
    isAsyncGeneratorFunction: typeof isAsyncGeneratorFunction;
    isPlainObject: typeof isPlainObject;
    isObject: typeof isObject;
    isFunction: typeof isFunction;
    isArraylike: typeof isArraylike;
    isNull: typeof isNull;
    isUndefined: typeof isUndefined;
    isNullish: typeof isNullish;
    isPrimitive: typeof isPrimitive;
    isIterator: typeof isIterator;
    isRegexp: typeof isRegexp;
    isElement: typeof isElement;
    isIterable: typeof isIterable;
    isAsyncIterable: typeof isAsyncIterable;
    isTypedArray: typeof isTypedArray;
    isGeneratorFunction: typeof isGeneratorFunction;
    isAsyncFunction: typeof isAsyncFunction;
    castArray: typeof castArray;
    compact: typeof compact;
    unique: typeof unique;
    count: typeof count;
    arrayDeepClone: typeof arrayDeepClone;
    initial: typeof initial;
    shuffle: typeof shuffle;
    min: typeof min;
    max: typeof max;
    arrayRepeat: typeof arrayRepeat;
    arrayCycle: typeof arrayCycle;
    arrayRange: typeof arrayRange;
    zip: typeof zip;
    unzip: typeof unzip;
    zipObj: typeof zipObj;
    arrayAdd: typeof arrayAdd;
    arrayClear: typeof arrayClear;
    arrayRemove: typeof arrayRemove;
    arrayRemoveBy: typeof arrayRemoveBy;
    arrayMerge: typeof arrayMerge;
    iterRange: typeof iterRange;
    iterCycle: typeof iterCycle;
    iterRepeat: typeof iterRepeat;
    slice: typeof slice;
    tail: typeof tail;
    item: typeof item;
    nth: typeof item;
    size: typeof size;
    first: typeof first;
    head: typeof first;
    last: typeof last;
    reverse: typeof reverse;
    sort: typeof sort;
    includes: typeof includes;
    findLast: typeof findLast;
    concat: typeof concat;
    join: typeof join;
    add: typeof add;
    sub: typeof sub;
    mul: typeof mul;
    div: typeof div;
    divMod: typeof divMod;
    mod: typeof mod;
    isFloat: typeof isFloat;
    toInteger: typeof toInteger;
    toIntegerOrInfinity: typeof toIntegerOrInfinity;
    sum: typeof sum;
    avg: typeof avg;
    product: typeof product;
    pow: typeof pow;
    clamp: typeof clamp;
    minmax: typeof clamp;
    isEven: typeof isEven;
    isOdd: typeof isOdd;
    signbit: typeof signbit;
    randomInt: typeof randomInt;
    randomFloat: typeof randomFloat;
    inRange: typeof inRange;
};
export default _default;
export { VERSION, BASE16, BASE32, BASE36, BASE58, BASE62, WORDSAFEALPHABET, assert, eq, gt, gte, lt, lte, tap, once, curry, pipe, compose, pick, omit, assoc, asyncNoop, asyncT, asyncF, asyncConstant, asyncIdentity, randomUUIDv7, delay, randomBoolean, deepAssign, sizeIn, unBind, bind, constant, identity, noop, T, F, timestampID, b64Encode, b64Decode, strCount, strTruncate, strPropercase, strTitlecase, strCapitalize, strUpFirst, strDownFirst, strReverse, strCodePoints, strFromCodePoints, strAt, strSplice, strHTMLRemoveTags, strHTMLEscape, strHTMLUnEscape, qsa, qs, domReady, domCreate, domToElement, domGetCSS, domSetCSS, domFadeIn, domFadeOut, domFadeToggle, domHide, domShow, domToggle, domIsHidden, domSiblings, domSiblingsPrev, domSiblingsLeft, domSiblingsNext, domSiblingsRight, importScript, importStyle, form2array, form2string, getDoNotTrack, getLocation, createFile, getFullscreen, setFullscreenOn, setFullscreenOff, domGetCSSVar, domSetCSSVar, domScrollToTop, domScrollToBottom, domScrollToElement, domClear, constructorOf, isNonNullable, isNonNullablePrimitive, isArrowFunction, isAsyncIterator, isTypedCollection, is, toSafeString, isPropertyKey, toPropertyKey, isIndex, toIndex, typeOf, isSameType, isSameInstance, isCoercedObject, isDeepStrictEqual, isEmpty, isProxy, isAsyncGeneratorFunction, isPlainObject, isObject, isFunction, isArraylike, isNull, isUndefined, isNullish, isPrimitive, isIterator, isRegexp, isElement, isIterable, isAsyncIterable, isTypedArray, isGeneratorFunction, isAsyncFunction, setCookie, getCookie, hasCookie, removeCookie, clearCookies, castArray, compact, unique, count, arrayDeepClone, initial, shuffle, min, max, arrayRepeat, arrayCycle, arrayRange, zip, unzip, zipObj, arrayAdd, arrayClear, arrayRemove, arrayRemoveBy, arrayMerge, iterRange, iterCycle, iterRepeat, slice, tail, item, nth, size, first, head, last, reverse, sort, includes, findLast, concat, join, add, sub, mul, div, divMod, mod, isFloat, toInteger, toIntegerOrInfinity, sum, avg, product, pow, clamp, minmax, isEven, isOdd, signbit, randomInt, randomFloat, inRange };
//# sourceMappingURL=celestra.d.ts.map