declare const VERSION = "Celestra v6.7.0 browser";
type ObjectLike = Record<PropertyKey, any>;
type Numeric = number | bigint;
type IterableLike = Iterable<any> | Iterator<any> | IterableIterator<any>;
type IterableLikeAndArrayLike = Iterable<any> | Iterator<any> | IterableIterator<any> | ArrayLike<any>;
type GeneratorLike = Iterable<any> | Iterator<any> | Generator<any, void, unknown>;
type Nullish = undefined | null;
type NonNullablePrimitive = boolean | number | bigint | string | symbol;
type Primitive = Nullish | NonNullablePrimitive;
type Comparable = number | bigint | string | boolean | Date;
type AsyncFunction<T> = (...args: ReadonlyArray<any>) => Promise<T>;
type ArrowFunction<Args extends any[] = any[], R = any> = (this: void, ...args: Args) => R;
type TypedArray = Exclude<ArrayBufferView, DataView>;
type ClearCookiesOptions = {
    path?: string | undefined;
    domain?: string | undefined;
    secure?: boolean | undefined;
    SameSite?: string | undefined;
    HttpOnly?: boolean | undefined;
};
declare const BASE16 = "0123456789ABCDEF";
declare const BASE32 = "234567ABCDEFGHIJKLMNOPQRSTUVWXYZ";
declare const BASE36 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
declare const BASE58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
declare const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
declare const WORDSAFEALPHABET = "23456789CFGHJMPQRVWXcfghjmpqvwx";
declare function assert(condition: unknown, message?: unknown): asserts condition;
declare const eq: (value1: unknown, value2: unknown) => boolean;
declare const gt: (value1: Comparable, value2: Comparable) => boolean;
declare const gte: (value1: Comparable, value2: Comparable) => boolean;
declare const lt: (value1: Comparable, value2: Comparable) => boolean;
declare const lte: (value1: Comparable, value2: Comparable) => boolean;
declare const tap: (callback: Function) => any;
declare function once(callback: Function): Function;
declare function curry(callback: Function): Function;
declare const pipe: (...functions: Function[]) => Function;
declare const compose: (...functions: Function[]) => Function;
declare const pick: (obj: ObjectLike, keys: string[]) => ObjectLike;
declare const omit: (obj: ObjectLike, keys: string[]) => ObjectLike;
declare const assoc: (obj: ObjectLike, key: string, value: unknown) => ObjectLike;
declare function asyncNoop(): Promise<void>;
declare function asyncT(): Promise<boolean>;
declare function asyncF(): Promise<boolean>;
declare function asyncConstant<T>(value: T): AsyncFunction<T>;
declare function asyncIdentity(value: unknown): Promise<any>;
declare function randomUUIDv7(v4?: boolean): string;
declare const delay: (milisec: number) => Promise<void>;
declare const randomBoolean: () => boolean;
declare const getUrlVars: (str?: string) => Object;
declare const obj2string: (obj: any) => string;
declare function extend<T extends object, U extends object>(target: T, source: U): T & U;
declare function extend<T extends object, U extends object, V extends object>(target: T, s1: U, s2: V): T & U & V;
declare function extend<T extends object>(deep: true, target: T, ...sources: any[]): T;
declare function extend<T extends object>(deep: false, target: T, ...sources: any[]): T;
declare function extend(target: object, ...sources: any[]): object;
declare const sizeIn: (obj: object) => number;
declare const unBind: (callback: Function) => Function;
declare const bind: (thisArg: any, ...argArray: any[]) => any;
declare const constant: <T>(value: T) => (() => T);
declare const identity: <T>(value: T) => T;
declare function noop(): void;
declare const T: () => boolean;
declare const F: () => boolean;
declare function nanoid(size?: number, alphabet?: string): string;
declare function timestampID(size?: number, alphabet?: string): string;
declare function b64Encode(str: any): string;
declare function b64Decode(str: any): string;
declare function strCount(str: unknown, substr: unknown): number;
declare function strTruncate(str: any, newLength: number, omission?: string): string;
declare const strPropercase: (str: any) => string;
declare const strTitlecase: (str: any) => string;
declare function strCapitalize(str: any): string;
declare function strUpFirst(str: any): string;
declare function strDownFirst(str: any): string;
declare const strReverse: (str: unknown) => string;
declare const strCodePoints: (str: any) => any[];
declare const strFromCodePoints: ([...array]: Iterable<number>) => string;
declare function strAt(str: string, index: number, newChar?: string): string;
declare const strSplice: (str: string, index: number, count: number, ...add: any[]) => string;
declare const strHTMLRemoveTags: (str: any) => string;
declare const strHTMLEscape: (str: any) => string;
declare const strHTMLUnEscape: (str: string) => string;
declare const qsa: (str: string, context?: Document | HTMLElement) => any[];
declare const qs: (str: string, context?: Document | Element) => HTMLElement | null;
declare function domReady(callback: Function): void;
declare function domCreate(elementType: string | ObjectLike, properties: object, innerHTML: string): HTMLElement;
declare function domToElement(str: string): Element | null;
declare const domGetCSS: (element: Element, property: string | number) => string | CSSStyleDeclaration;
declare function domSetCSS(element: HTMLElement, property: string | object, value: string): void;
declare function domFadeIn(element: HTMLElement, duration: number, display: string): void;
declare function domFadeOut(element: HTMLElement, duration: number): void;
declare function domFadeToggle(element: HTMLElement, duration: number, display?: string): void;
declare const domHide: (element: HTMLElement) => any;
declare const domShow: (element: HTMLElement, display?: string) => any;
declare function domToggle(element: HTMLElement, display?: string): void;
declare const domIsHidden: (element: Element) => boolean;
declare const domSiblings: (element: Element) => Element[];
declare const domSiblingsPrev: (element: Element) => Element[];
declare const domSiblingsLeft: (element: Element) => Element[];
declare const domSiblingsNext: (element: Element) => Element[];
declare const domSiblingsRight: (element: HTMLElement) => Element[];
declare function importScript(...scripts: string[]): void;
declare function importStyle(...styles: string[]): void;
declare function form2array(form: HTMLFormElement): object[];
declare function form2string(form: HTMLFormElement): string;
declare const getDoNotTrack: () => boolean;
declare function getLocation(successCallback: Function, errorCallback?: Function): void;
declare function createFile(filename: string, content: string, dataType: string): void;
declare const getFullscreen: () => Document | HTMLElement | undefined;
declare function setFullscreenOn(element: HTMLElement | string): void;
declare function setFullscreenOff(): void;
declare const domGetCSSVar: (name: string) => string;
declare const domSetCSSVar: (name: string, value: string | null) => void;
declare const domScrollToTop: () => void;
declare const domScrollToBottom: () => void;
declare const domScrollToElement: (element: Element, top?: boolean) => void;
declare const domClear: (element: Element) => void;
declare const isNonNullable: (value: unknown) => value is NonNullable<unknown>;
declare const isNonNullablePrimitive: (value: unknown) => value is NonNullablePrimitive;
declare function isArrowFunction(value: unknown): value is ArrowFunction;
declare const isAsyncIterator: (value: unknown) => value is AsyncIterator<unknown>;
declare function isTypedCollection(iter: IterableLike, expectedType: string | Function | Array<string | Function>, Throw?: boolean): boolean;
declare function is(value: any, expectedType?: string | Function | Array<string | Function> | undefined, Throw?: boolean): string | Function | boolean;
declare function toObject(value: unknown): Object | symbol | Function;
declare function toPrimitive(value: unknown): any;
declare function toSafeString(value: unknown): string;
declare const isPropertyKey: (value: unknown) => value is PropertyKey;
declare const toPropertyKey: (value: unknown) => PropertyKey;
declare const isIndex: (value: unknown) => value is number;
declare const isLength: (value: unknown) => value is number;
declare function toIndex(value: any): number;
declare function toLength(value: any): number;
declare const typeOf: (value: unknown) => string;
declare const isSameType: (value1: any, value2: any) => boolean;
declare const isSameInstance: (value1: any, value2: any, Contructor: Function) => boolean;
declare function isCoercedObject(value: unknown): Function | boolean;
declare function isDeepStrictEqual(value1: any, value2: any): boolean;
declare function isEmpty(value: any): boolean;
declare const isProxy: (value: any) => boolean;
declare const isAsyncGeneratorFunction: (value: unknown) => value is AsyncGeneratorFunction;
declare const isPlainObject: (value: unknown) => boolean;
declare const isObject: (value: unknown) => value is object;
declare const isFunction: (value: unknown) => value is Function;
declare function isArraylike<T>(value: unknown): value is ArrayLike<T>;
declare const isNull: (value: unknown) => value is null;
declare const isUndefined: (value: unknown) => value is undefined;
declare const isNullish: (value: unknown) => value is Nullish;
declare const isPrimitive: (value: unknown) => value is Primitive;
declare const isIterator: <T>(value: unknown) => value is Iterator<T>;
declare const isRegexp: (value: unknown) => value is RegExp;
declare const isElement: (value: any) => boolean;
declare const isIterable: (value: unknown) => value is Iterable<any>;
declare const isAsyncIterable: <T>(value: unknown) => value is AsyncIterable<T>;
declare const isTypedArray: (value: unknown) => value is TypedArray;
declare const isGeneratorFunction: (value: unknown) => value is GeneratorFunction;
declare const isAsyncFunction: <T>(value: unknown) => value is AsyncFunction<T>;
declare function setCookie(name: string | ObjectLike, value: string, hours: number | undefined, path: string | undefined, domain: string, secure: boolean, SameSite: string | undefined, HttpOnly: boolean): void;
declare function getCookie(name: string): string | null | ObjectLike;
declare function hasCookie(name: string): boolean;
declare function removeCookie(name: string | ObjectLike, path: string | undefined, domain: string, secure: boolean, SameSite: string | undefined, HttpOnly: boolean): boolean;
declare function clearCookies(path?: string | ClearCookiesOptions, domain?: string, secure?: boolean, SameSite?: string | undefined, HttpOnly?: boolean): void;
declare const castArray: (value: unknown) => any[];
declare const compact: (iter: IterableLikeAndArrayLike) => any[];
declare function unique(iter: IterableLike, resolver?: string | Function | null | undefined): any[] | void;
declare function count(iter: IterableLike, callback: Function): number;
declare function arrayDeepClone([...array]: any[]): any[];
declare const initial: ([...array]: any[]) => unknown[];
declare function shuffle([...array]: any[]): unknown[];
declare const partition: ([...array]: any[], callback: Function) => any[];
declare const min: (...args: any[]) => any;
declare const max: (...args: any[]) => any;
declare const arrayRepeat: (value: unknown, num?: number) => any[];
declare const arrayCycle: ([...array]: any[], num?: number) => any[];
declare const arrayRange: (start?: number, end?: number, step?: number) => any[];
declare function zip(...args: any[]): any[];
declare const unzip: ([...array]: any[]) => any[];
declare function zipObj([...array1]: any[], [...array2]: any[]): ObjectLike;
declare const arrayAdd: (array: any[], value: unknown) => boolean;
declare function arrayClear(array: any[]): any[];
declare function arrayRemove(array: any[], value: unknown, all?: boolean): boolean;
declare function arrayRemoveBy(array: any[], callback: Function, all?: boolean): boolean;
declare function arrayMerge(target: any[], ...sources: any[]): any[];
declare function iterRange(start?: number, step?: number, end?: number): Generator<number, void, unknown>;
declare function iterCycle([...array]: any[], num?: number): GeneratorLike;
declare function iterRepeat(value: unknown, num?: number): GeneratorLike;
declare function takeWhile<T>(iter: IterableLike, callback: Function): GeneratorLike;
declare function dropWhile<T>(iter: IterableLike, callback: Function): GeneratorLike;
declare function take<T>(iter: IterableLike, num?: number): GeneratorLike;
declare function drop<T>(iter: IterableLike, num?: number): GeneratorLike;
declare function forEach(iter: IterableLike, callback: Function): void;
declare function forEachRight([...array]: any[], callback: Function): void;
declare function map(iter: IterableLike, callback: Function): GeneratorLike;
declare function filter(iter: IterableLike, callback: Function): GeneratorLike;
declare function reject(iter: IterableLike, callback: Function): GeneratorLike;
declare function slice<T>(iter: IterableLike, begin?: number, end?: number): GeneratorLike;
declare function tail<T>(input: IterableLike): GeneratorLike;
declare function item<T>(iter: IterableLike, pos: number): T | undefined;
declare function nth<T>(iter: IterableLike, pos: number): T | undefined;
declare function size(value: any): number;
declare function first<T>(input: IterableLike): T | undefined;
declare function head<T>(input: IterableLike): T | undefined;
declare const last: ([...array]: any[]) => any;
declare function reverse([...array]: any[]): GeneratorLike;
declare const sort: ([...array]: Iterable<any, void, undefined>, numbers?: boolean) => any[];
declare function includes(collection: any, value: any, comparator?: Function): boolean;
declare const find: ([...array]: any[], callback: Function) => unknown;
declare const findLast: ([...array]: any[], callback: Function) => unknown;
declare const every: ([...array]: any[], callback: Function) => boolean;
declare const some: ([...array]: any[], callback: Function) => boolean;
declare const none: ([...array]: any[], callback: Function) => boolean;
declare const takeRight: ([...array]: any[], num?: number) => any[];
declare function takeRightWhile([...array]: any[], callback: Function): GeneratorLike;
declare const dropRight: ([...array]: any[], num?: number) => any[];
declare function dropRightWhile([...array]: any[], callback: Function): GeneratorLike;
declare function concat(...args: any[]): GeneratorLike;
declare function reduce(iter: IterableLike, callback: Function, initialvalue?: any): any;
declare function enumerate(iter: IterableLike, offset?: number): GeneratorLike;
declare function flat(iter: IterableLike): GeneratorLike;
declare function join(iter: IterableLike, separator?: string): string;
declare const withOut: ([...array]: any[], [...filterValues]: any[]) => any[];
declare function add(value1: number, value2: number): number;
declare function add(value1: bigint, value2: bigint): bigint;
declare function sub(value1: number, value2: number): number;
declare function sub(value1: bigint, value2: bigint): bigint;
declare function mul(value1: number, value2: number): number;
declare function mul(value1: bigint, value2: bigint): bigint;
declare function div(value1: number, value2: number): number;
declare function div(value1: bigint, value2: bigint): bigint;
declare function divMod(value1: number, value2: number): number;
declare function divMod(value1: bigint, value2: bigint): bigint;
declare function mod(value1: number, value2: number): number;
declare function mod(value1: bigint, value2: bigint): bigint;
declare const isFloat: (value: unknown) => boolean;
declare function toInteger(value: any): number;
declare const toIntegerOrInfinity: (value: unknown) => number;
declare function sum(...args: any[]): any;
declare const avg: (...args: number[]) => number;
declare function product(first: number, ...args: number[]): number;
declare function product(first: bigint, ...args: bigint[]): bigint;
declare function pow(base: number, power: number): number;
declare function pow(base: bigint, power: bigint): bigint;
declare function clamp(value: number, min: number, max: number): number;
declare function clamp(value: bigint, min: bigint, max: bigint): bigint;
declare function minmax(value: number, min: number, max: number): number;
declare function minmax(value: bigint, min: bigint, max: bigint): bigint;
declare function isEven(value: unknown): boolean;
declare function isOdd(value: unknown): boolean;
declare const toInt8: (value: unknown) => number;
declare const toUInt8: (value: unknown) => number;
declare const toInt16: (value: unknown) => number;
declare const toUInt16: (value: unknown) => number;
declare const toInt32: (value: unknown) => number;
declare const toUInt32: (value: unknown) => number;
declare const toBigInt64: (value: any | bigint) => bigint;
declare const toBigUInt64: (value: unknown) => bigint;
declare const toFloat32: (value: unknown) => number;
declare const isInt8: (value: unknown | number) => boolean;
declare const isUInt8: (value: unknown | number) => boolean;
declare const isInt16: (value: unknown) => boolean;
declare const isUInt16: (value: unknown) => boolean;
declare const isInt32: (value: unknown) => boolean;
declare const isUInt32: (value: unknown | number) => boolean;
declare const isBigInt64: (value: unknown) => boolean;
declare const isBigUInt64: (value: unknown | Numeric) => boolean;
declare const toFloat16: (value: unknown) => number;
declare const isFloat16: (value: unknown | Numeric) => boolean;
declare const signbit: (value: unknown | Numeric) => boolean;
declare function randomInt(min?: number | undefined, max?: number | null | undefined): number;
declare function randomFloat(min?: number | undefined, max?: number | null | undefined): number;
declare function inRange(value: number, min: number, max: number): boolean;
declare function inRange(value: bigint, min: bigint, max: number): boolean;
declare const _default: {
    VERSION: string;
    BASE16: string;
    BASE32: string;
    BASE36: string;
    BASE58: string;
    BASE62: string;
    WORDSAFEALPHABET: string;
    assert: typeof assert;
    eq: (value1: unknown, value2: unknown) => boolean;
    gt: (value1: Comparable, value2: Comparable) => boolean;
    gte: (value1: Comparable, value2: Comparable) => boolean;
    lt: (value1: Comparable, value2: Comparable) => boolean;
    lte: (value1: Comparable, value2: Comparable) => boolean;
    tap: (callback: Function) => any;
    once: typeof once;
    curry: typeof curry;
    pipe: (...functions: Function[]) => Function;
    compose: (...functions: Function[]) => Function;
    pick: (obj: ObjectLike, keys: string[]) => ObjectLike;
    omit: (obj: ObjectLike, keys: string[]) => ObjectLike;
    assoc: (obj: ObjectLike, key: string, value: unknown) => ObjectLike;
    asyncNoop: typeof asyncNoop;
    asyncT: typeof asyncT;
    asyncF: typeof asyncF;
    asyncConstant: typeof asyncConstant;
    asyncIdentity: typeof asyncIdentity;
    randomUUIDv7: typeof randomUUIDv7;
    delay: (milisec: number) => Promise<void>;
    randomBoolean: () => boolean;
    getUrlVars: (str?: string) => Object;
    obj2string: (obj: any) => string;
    extend: typeof extend;
    sizeIn: (obj: object) => number;
    unBind: (callback: Function) => Function;
    bind: (thisArg: any, ...argArray: any[]) => any;
    constant: <T>(value: T) => (() => T);
    identity: <T>(value: T) => T;
    noop: typeof noop;
    T: () => boolean;
    F: () => boolean;
    nanoid: typeof nanoid;
    timestampID: typeof timestampID;
    b64Encode: typeof b64Encode;
    b64Decode: typeof b64Decode;
    strCount: typeof strCount;
    strTruncate: typeof strTruncate;
    strPropercase: (str: any) => string;
    strTitlecase: (str: any) => string;
    strCapitalize: typeof strCapitalize;
    strUpFirst: typeof strUpFirst;
    strDownFirst: typeof strDownFirst;
    strReverse: (str: unknown) => string;
    strCodePoints: (str: any) => any[];
    strFromCodePoints: ([...array]: Iterable<number>) => string;
    strAt: typeof strAt;
    strSplice: (str: string, index: number, count: number, ...add: any[]) => string;
    strHTMLRemoveTags: (str: any) => string;
    strHTMLEscape: (str: any) => string;
    strHTMLUnEscape: (str: string) => string;
    qsa: (str: string, context?: Document | HTMLElement) => any[];
    qs: (str: string, context?: Document | Element) => HTMLElement | null;
    domReady: typeof domReady;
    domCreate: typeof domCreate;
    domToElement: typeof domToElement;
    domGetCSS: (element: Element, property: string | number) => string | CSSStyleDeclaration;
    domSetCSS: typeof domSetCSS;
    domFadeIn: typeof domFadeIn;
    domFadeOut: typeof domFadeOut;
    domFadeToggle: typeof domFadeToggle;
    domHide: (element: HTMLElement) => any;
    domShow: (element: HTMLElement, display?: string) => any;
    domToggle: typeof domToggle;
    domIsHidden: (element: Element) => boolean;
    domSiblings: (element: Element) => Element[];
    domSiblingsPrev: (element: Element) => Element[];
    domSiblingsLeft: (element: Element) => Element[];
    domSiblingsNext: (element: Element) => Element[];
    domSiblingsRight: (element: HTMLElement) => Element[];
    importScript: typeof importScript;
    importStyle: typeof importStyle;
    form2array: typeof form2array;
    form2string: typeof form2string;
    getDoNotTrack: () => boolean;
    getLocation: typeof getLocation;
    createFile: typeof createFile;
    getFullscreen: () => Document | HTMLElement | undefined;
    setFullscreenOn: typeof setFullscreenOn;
    setFullscreenOff: typeof setFullscreenOff;
    domGetCSSVar: (name: string) => string;
    domSetCSSVar: (name: string, value: string | null) => void;
    domScrollToTop: () => void;
    domScrollToBottom: () => void;
    domScrollToElement: (element: Element, top?: boolean) => void;
    domClear: (element: Element) => void;
    isNonNullable: (value: unknown) => value is NonNullable<unknown>;
    isNonNullablePrimitive: (value: unknown) => value is NonNullablePrimitive;
    isArrowFunction: typeof isArrowFunction;
    isAsyncIterator: (value: unknown) => value is AsyncIterator<unknown>;
    isTypedCollection: typeof isTypedCollection;
    is: typeof is;
    toObject: typeof toObject;
    toPrimitive: typeof toPrimitive;
    toSafeString: typeof toSafeString;
    isPropertyKey: (value: unknown) => value is PropertyKey;
    toPropertyKey: (value: unknown) => PropertyKey;
    isIndex: (value: unknown) => value is number;
    isLength: (value: unknown) => value is number;
    toIndex: typeof toIndex;
    toLength: typeof toLength;
    typeOf: (value: unknown) => string;
    isSameType: (value1: any, value2: any) => boolean;
    isSameInstance: (value1: any, value2: any, Contructor: Function) => boolean;
    isCoercedObject: typeof isCoercedObject;
    isDeepStrictEqual: typeof isDeepStrictEqual;
    isEmpty: typeof isEmpty;
    isProxy: (value: any) => boolean;
    isAsyncGeneratorFunction: (value: unknown) => value is AsyncGeneratorFunction;
    isPlainObject: (value: unknown) => boolean;
    isObject: (value: unknown) => value is object;
    isFunction: (value: unknown) => value is Function;
    isArraylike: typeof isArraylike;
    isNull: (value: unknown) => value is null;
    isUndefined: (value: unknown) => value is undefined;
    isNullish: (value: unknown) => value is Nullish;
    isPrimitive: (value: unknown) => value is Primitive;
    isIterator: <T>(value: unknown) => value is Iterator<T>;
    isRegexp: (value: unknown) => value is RegExp;
    isElement: (value: any) => boolean;
    isIterable: (value: unknown) => value is Iterable<any>;
    isAsyncIterable: <T>(value: unknown) => value is AsyncIterable<T>;
    isTypedArray: (value: unknown) => value is TypedArray;
    isGeneratorFunction: (value: unknown) => value is GeneratorFunction;
    isAsyncFunction: <T>(value: unknown) => value is AsyncFunction<T>;
    setCookie: typeof setCookie;
    getCookie: typeof getCookie;
    hasCookie: typeof hasCookie;
    removeCookie: typeof removeCookie;
    clearCookies: typeof clearCookies;
    castArray: (value: unknown) => any[];
    compact: (iter: IterableLikeAndArrayLike) => any[];
    unique: typeof unique;
    count: typeof count;
    arrayDeepClone: typeof arrayDeepClone;
    initial: ([...array]: any[]) => unknown[];
    shuffle: typeof shuffle;
    partition: ([...array]: any[], callback: Function) => any[];
    min: (...args: any[]) => any;
    max: (...args: any[]) => any;
    arrayRepeat: (value: unknown, num?: number) => any[];
    arrayCycle: ([...array]: any[], num?: number) => any[];
    arrayRange: (start?: number, end?: number, step?: number) => any[];
    zip: typeof zip;
    unzip: ([...array]: any[]) => any[];
    zipObj: typeof zipObj;
    arrayAdd: (array: any[], value: unknown) => boolean;
    arrayClear: typeof arrayClear;
    arrayRemove: typeof arrayRemove;
    arrayRemoveBy: typeof arrayRemoveBy;
    arrayMerge: typeof arrayMerge;
    iterRange: typeof iterRange;
    iterCycle: typeof iterCycle;
    iterRepeat: typeof iterRepeat;
    takeWhile: typeof takeWhile;
    dropWhile: typeof dropWhile;
    take: typeof take;
    drop: typeof drop;
    forEach: typeof forEach;
    forEachRight: typeof forEachRight;
    map: typeof map;
    filter: typeof filter;
    reject: typeof reject;
    slice: typeof slice;
    tail: typeof tail;
    item: typeof item;
    nth: typeof nth;
    size: typeof size;
    first: typeof first;
    head: typeof head;
    last: ([...array]: any[]) => any;
    reverse: typeof reverse;
    sort: ([...array]: Iterable<any, void, undefined>, numbers?: boolean) => any[];
    includes: typeof includes;
    find: ([...array]: any[], callback: Function) => unknown;
    findLast: ([...array]: any[], callback: Function) => unknown;
    every: ([...array]: any[], callback: Function) => boolean;
    some: ([...array]: any[], callback: Function) => boolean;
    none: ([...array]: any[], callback: Function) => boolean;
    takeRight: ([...array]: any[], num?: number) => any[];
    takeRightWhile: typeof takeRightWhile;
    dropRight: ([...array]: any[], num?: number) => any[];
    dropRightWhile: typeof dropRightWhile;
    concat: typeof concat;
    reduce: typeof reduce;
    enumerate: typeof enumerate;
    flat: typeof flat;
    join: typeof join;
    withOut: ([...array]: any[], [...filterValues]: any[]) => any[];
    add: typeof add;
    sub: typeof sub;
    mul: typeof mul;
    div: typeof div;
    divMod: typeof divMod;
    mod: typeof mod;
    isFloat: (value: unknown) => boolean;
    toInteger: typeof toInteger;
    toIntegerOrInfinity: (value: unknown) => number;
    sum: typeof sum;
    avg: (...args: number[]) => number;
    product: typeof product;
    pow: typeof pow;
    clamp: typeof clamp;
    minmax: typeof minmax;
    isEven: typeof isEven;
    isOdd: typeof isOdd;
    toInt8: (value: unknown) => number;
    toUInt8: (value: unknown) => number;
    toInt16: (value: unknown) => number;
    toUInt16: (value: unknown) => number;
    toInt32: (value: unknown) => number;
    toUInt32: (value: unknown) => number;
    toBigInt64: (value: any | bigint) => bigint;
    toBigUInt64: (value: unknown) => bigint;
    toFloat32: (value: unknown) => number;
    isInt8: (value: unknown | number) => boolean;
    isUInt8: (value: unknown | number) => boolean;
    isInt16: (value: unknown) => boolean;
    isUInt16: (value: unknown) => boolean;
    isInt32: (value: unknown) => boolean;
    isUInt32: (value: unknown | number) => boolean;
    isBigInt64: (value: unknown) => boolean;
    isBigUInt64: (value: unknown | Numeric) => boolean;
    toFloat16: (value: unknown) => number;
    isFloat16: (value: unknown | Numeric) => boolean;
    signbit: (value: unknown | Numeric) => boolean;
    randomInt: typeof randomInt;
    randomFloat: typeof randomFloat;
    inRange: typeof inRange;
};
export default _default;
export { VERSION, BASE16, BASE32, BASE36, BASE58, BASE62, WORDSAFEALPHABET, assert, eq, gt, gte, lt, lte, tap, once, curry, pipe, compose, pick, omit, assoc, asyncNoop, asyncT, asyncF, asyncConstant, asyncIdentity, randomUUIDv7, delay, randomBoolean, getUrlVars, obj2string, extend, sizeIn, unBind, bind, constant, identity, noop, T, F, nanoid, timestampID, b64Encode, b64Decode, strCount, strTruncate, strPropercase, strTitlecase, strCapitalize, strUpFirst, strDownFirst, strReverse, strCodePoints, strFromCodePoints, strAt, strSplice, strHTMLRemoveTags, strHTMLEscape, strHTMLUnEscape, qsa, qs, domReady, domCreate, domToElement, domGetCSS, domSetCSS, domFadeIn, domFadeOut, domFadeToggle, domHide, domShow, domToggle, domIsHidden, domSiblings, domSiblingsPrev, domSiblingsLeft, domSiblingsNext, domSiblingsRight, importScript, importStyle, form2array, form2string, getDoNotTrack, getLocation, createFile, getFullscreen, setFullscreenOn, setFullscreenOff, domGetCSSVar, domSetCSSVar, domScrollToTop, domScrollToBottom, domScrollToElement, domClear, isNonNullable, isNonNullablePrimitive, isArrowFunction, isAsyncIterator, isTypedCollection, is, toObject, toPrimitive, toSafeString, isPropertyKey, toPropertyKey, isIndex, isLength, toIndex, toLength, typeOf, isSameType, isSameInstance, isCoercedObject, isDeepStrictEqual, isEmpty, isProxy, isAsyncGeneratorFunction, isPlainObject, isObject, isFunction, isArraylike, isNull, isUndefined, isNullish, isPrimitive, isIterator, isRegexp, isElement, isIterable, isAsyncIterable, isTypedArray, isGeneratorFunction, isAsyncFunction, setCookie, getCookie, hasCookie, removeCookie, clearCookies, castArray, compact, unique, count, arrayDeepClone, initial, shuffle, partition, min, max, arrayRepeat, arrayCycle, arrayRange, zip, unzip, zipObj, arrayAdd, arrayClear, arrayRemove, arrayRemoveBy, arrayMerge, iterRange, iterCycle, iterRepeat, takeWhile, dropWhile, take, drop, forEach, forEachRight, map, filter, reject, slice, tail, item, nth, size, first, head, last, reverse, sort, includes, find, findLast, every, some, none, takeRight, takeRightWhile, dropRight, dropRightWhile, concat, reduce, enumerate, flat, join, withOut, add, sub, mul, div, divMod, mod, isFloat, toInteger, toIntegerOrInfinity, sum, avg, product, pow, clamp, minmax, isEven, isOdd, toInt8, toUInt8, toInt16, toUInt16, toInt32, toUInt32, toBigInt64, toBigUInt64, toFloat32, isInt8, isUInt8, isInt16, isUInt16, isInt32, isUInt32, isBigInt64, isBigUInt64, toFloat16, isFloat16, signbit, randomInt, randomFloat, inRange };
//# sourceMappingURL=celestra.browser.d.ts.map